# Generated by Django 4.1.3 on 2023-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500, null=True)),
                ('opening_hours', models.TextField(max_length=500, null=True)),
                ('whatsappNumber', models.CharField(max_length=200, null=True)),
                ('facebookLink', models.CharField(max_length=200, null=True)),
                ('instagramLink', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
